### ISSUE TITLE
Grafana Plugin

### ISSUE THREAD

**Issue by melgl** [chaos-mesh/chaos-mesh-datasource#33]
Hi there! I noticed a few broken images on the Grafana [Plugin page](https://grafana.com/grafana/plugins/yeya24-chaosmesh-datasource/) and also see that the plugin is not signed. 

I'd like to confirm that everything is in good state with this plugin so I can recommend it to Grafana Cloud users and would love to help out with [getting this signed](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/) if you'd like.

**Comment by g1eny0ung** [comment]
Thx. We already sign it in this PR: https://github.com/grafana/grafana-plugin-repository/pull/879. Still waiting for it to be merged 😢.

**Comment by g1eny0ung** [comment]
Close due to already signed.
