### ISSUE TITLE
installation command on grafana plugin page is not correct

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh-datasource#35]
ref: https://grafana.com/grafana/plugins/yeya24-chaosmesh-datasource/

![Screenshot_20210726_175215](https://user-images.githubusercontent.com/20221408/126970030-ec43b1ec-fc22-46d7-9086-5b9199b6a95a.png)

it seems https://github.com/chaos-mesh/chaos-mesh-datasource/pull/34 is not applied.

**Comment by nikolaykolev** [comment]
I've just hit that issue. Took me good 40-50 min banging my head against the wall until I got here and saw the mistake... just to make it easier for google to find it, the right chaos mesh grafana plugin installation command is
grafana-cli plugins install yeya24-chaosmesh-datasource

and not

grafana-cli plugins install yeya24-chaos-mesh-datasource

**Comment by g1eny0ung** [comment]
> I've just hit that issue. Took me good 40-50 min banging my head against the wall until I got here and saw the mistake... just to make it easier for google to find it, the right chaos mesh grafana plugin installation command is grafana-cli plugins install yeya24-chaosmesh-datasource
> 
> and not
> 
> grafana-cli plugins install yeya24-chaos-mesh-datasource

Sorry about that 😢, this is our mistake. We will update the plugin README ASAP.
