### ISSUE TITLE
how to  intgration chaos-mesh with user-permissions enabled

### ISSUE THREAD

**Issue by liya2017** [chaos-mesh/chaos-mesh-datasource#39]
Hi, I created the RBAC for chaos-mesh followed this doc https://chaos-mesh.org/zh/docs/manage-user-permissions/
and added the chaos-mesh datasource in grafana, but I got error `error.api.bad_request: token is empty]()`
How can fix it？

**Comment by WangXiangUSTC** [comment]
1. Get a token
The token is generated by Kubernetes, you need to create a ServiceAccount, and bind it with a role. And then get the token. Refer to https://chaos-mesh.org/zh/docs/1.1.4/user_guides/dashboard/#get-the-token 

2. Add a header for request at `Custom HTTP Headers` for Chaos Mesh data source in Grafana

The header's format is `Authorization: Bearer <token>`, you need to replace `<token>` with the token value you got in 1. And then click `Add header` at `Custom HTTP Headers`, fill it with `Authorization: Bearer <token>`


![181647570483_ pic](https://user-images.githubusercontent.com/5793595/158926002-765ea397-c75a-4d2a-9afe-45cbc644b89c.jpg)

**Comment by g1eny0ung** [comment]
I will close this issue to mark this issue has been resolved. Feel free to reopen it if there have some related problems.
