### ISSUE TITLE
use `Experiment` in `variables` doesn't work

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh-datasource#42]
![EzmWraHaBc](https://user-images.githubusercontent.com/5793595/170638212-2c390974-298f-4f76-a9b0-bd3fb6f18101.png)

I want to use `Experiment` as `variable`, so that I can get chaos metrics depending on a specific experiment name, but it doesn't work.

**Comment by g1eny0ung** [comment]
I have already released a draft [`v2.2.0`](https://github.com/chaos-mesh/datasource/releases/tag/v2.2.0) version to fix this problem. Now you can get experiments under different namespaces as variables by specifying queries.

I will close this issue for now. Feel free to reopen this issue if you still encounter this problem in the new release.
