### ISSUE TITLE
Grafana query for chaos mesh gives error.api.bad_request: token is empty

### ISSUE THREAD

**Issue by himeshkothari** [chaos-mesh/chaos-mesh-datasource#52]
I have installed chaos-mesh in my GKE cluster using helm chart. 

As per https://github.com/chaos-mesh/datasource, I have been able to add Chaos Mesh Data Source but when I try to query data in Grafana using it I receive the error as below

![image](https://user-images.githubusercontent.com/69669168/209553112-861f1ea6-e622-4b53-851b-cbeb36d94acb.png)

I think it might be related to user credentials who has access via Google OAuth to Chaos Mesh. How do I control this using API requests sent by Grafana to Chaos Mesh to retrieve data ?

**Comment by himeshkothari** [comment]
Hi, Any update on this ?

**Comment by sangugwad1993** [comment]
Any updates or do we have a solution to this? I am also stuck on the same.

**Comment by fzyzcjy** [comment]
I am also seeing the same issue. Is there anyone who successfully use this?

**Comment by sarathsprakash** [comment]
Just add the `Custom HTTP Header`  **Authorization** and values Chaos-mesh ServiceAccount generated token as Bearer.

> Header: Authorization
> Value : Bearer \<ServiceAccount Token\>

<img width="317" alt="bearer" src="https://github.com/chaos-mesh/datasource/assets/5259733/6de83f0a-0cf8-4b6b-aa87-a4f0c59bdf6a">

**Comment by g1eny0ung** [comment]
Hi, guys. I realized that this part of the documentation is missing. I'll update the related docs about adding the token to perform requests when deploying Chaos Mesh with `dashboard.securityMode=true`.

**Comment by g1eny0ung** [comment]
Added. https://github.com/chaos-mesh/datasource#authentication
